---
title: "Mini-Project 2"
author: "Angelica Estrada"
date: "October 31, 2017"
output: html_document
---

<!-- GitHub Steps: Pull, Stage, Commit, Push -->

## Loading the data

This project is so interesting and relevant to my life!

```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r}
library(tidyverse)
glimpse(house_elections)
```

```{r}
glimpse(candidates)
```

```{r}
glimpse(committees)
```

```{r}
glimpse(contributions)
```

<!-- SKIP THIS
```{r}
# Create candidates data set for only year 2011
can2011 <- candidates %>%
  filter(cand_election_yr == 2011)

# Repeat for year 2012
can2012 <- candidates %>%
  filter(cand_election_yr == 2012)

```

```{r}
# Check for duplicated candidates in `can2011`
any(duplicated(can2011$cand_name))

# Check for duplicated candidates in `can2012`
any(duplicated(can2012$cand_name))

```
-->

## FOR YEAR 2011
```{r}
# Find number of candidates who ran for P,H,S
can_num2011 <- candidates %>%
  filter(cand_election_yr == 2011) %>%
  group_by(cand_office) %>%
  summarise(num = n())
can_num2011
```

```{r}
# Create dataset of candidates who ran for President
pres2011 <- candidates %>%
  filter(cand_election_yr == 2011 & cand_office == "P") 

# Create dataset of candidates who ran for House
house2011 <- candidates %>%
  filter(cand_election_yr == 2011 & cand_office == "H") 
 
# Check duplicates
any(duplicated(pres2011$cand_name))
any(duplicated(house2011$cand_name))

```

## FOR YEAR 2012

```{r}
# Find number of candidates who ran for P,H,S
can_num2012 <- candidates %>%
  filter(cand_election_yr == 2012) %>%
  group_by(cand_office) %>%
  summarise(num = n())
can_num2012
```


```{r}

# Create dataset of candidates who ran for President
pres2012 <- candidates %>%
  filter(cand_election_yr == 2012 & cand_office == "P") 
 
# Create dataset of candidates who ran for House
house2012 <- candidates %>%
  filter(cand_election_yr == 2012 & cand_office == "H") 
 
# Create dataset of candidates who ran for Senate
sen2012 <- candidates %>%
  filter(cand_election_yr == 2012 & cand_office == "S") 
 
# Check duplicates
any(duplicated(pres2012$cand_name))
any(duplicated(house2012$cand_name))
any(duplicated(sen2012$cand_name))
```
 
```{r}
# Check the duplicate in house2012
d <- house2012$cand_name[duplicated(house2012$cand_name)] 
d
```

```{r}
hancock <- house2012 %>%
  filter(cand_name == "HANCOCK, DAVID")

```

```{r}
dupes <- house2012 %>%
  filter(cand_name == "HANCOCK, DAVID" |
           cand_name == "AVERSA, ALAN" |
           cand_name == "BIBBS, JAMES" |
           cand_name == "LEWIS, DAVID" |
           cand_name == "FOSTER, JAMES" |
           cand_name == "SANCHEZ, DAVID" | 
           cand_name == "BRODHEAD, STEPHAN ANDREW" |
           cand_name == "HATHCOX, VALINDA")

dupes <- dupes %>%
  arrange(cand_name)

```

<!-- IGNORE (TRIED MAKING A FUNCTION INSTEAD OF MANUALLY CODING ABOVE)
```{r}
# Create duplicate function
dup_fun2012 <- function(name){
  house2012 %>%
  filter(cand_name == name)
}
```

```{r}
# Use lapply
lapply(d, dup_fun2012)
```
--> 
 



